# Generated by Django 6.0.7 on 2026-07-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestamo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('denegado', 'Denegado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=10)),
                ('plazo_de_solicitud', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
