# Generated by Django 6.0.7 on 2026-08-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='extension_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
