# Generated by Django 6.0.7 on 2026-08-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_extension_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='extension_estado',
            field=models.CharField(blank=True, choices=[('', 'Sin resolver'), ('aprobada', 'Aprobada'), ('denegada', 'Denegada')], max_length=10),
        ),
    ]
