# Generated by Django 6.0.7 on 2026-07-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255)),
                ('editorial', models.CharField(blank=True, max_length=255)),
                ('fecha_publicacion', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True)),
                ('nro_codigo', models.CharField(blank=True, max_length=50)),
                ('nro_inventario', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('disponibles', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(blank=True, choices=[('libro base', 'Libro base'), ('libro de consulta', 'Libro de consulta')], max_length=20)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
