# Generated by Django 6.0.7 on 2026-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='anio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
