# Generated by Django 6.0.7 on 2026-09-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_force_local_covers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imagen',
            field=models.TextField(blank=True),
        ),
    ]
